"""Multi-format export for research reports — DOCX, PPTX, LaTeX."""

from pathlib import Path

import mistune
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from pptx import Presentation
from pptx.util import Inches as PptxInches, Pt as PptxPt
import mistletoe
from mistletoe.latex_renderer import LaTeXRenderer


# ─── Markdown → DOCX ──────────────────────────────────────────────────────

def export_docx(markdown: str, output_path: str | Path, title: str = "Research Report") -> str:
    """
    Convert Markdown report to a formatted Word document.

    Args:
        markdown: Markdown content
        output_path: Output .docx file path
        title: Document title

    Returns:
        Absolute path to generated file
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = Document()

    # Title
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Parse markdown into AST
    parser = mistune.create_markdown(renderer=None)
    tokens = parser(markdown)

    _render_tokens_to_docx(doc, tokens)

    doc.save(str(output_path))
    return str(output_path.resolve())


def _render_tokens_to_docx(doc: Document, tokens: list) -> None:
    """Render mistune AST tokens into a Word document."""
    for token in tokens:
        ttype = token.get("type", "")

        if ttype == "heading":
            level = token.get("attrs", {}).get("level", 1)
            text = _extract_text(token.get("children", []))
            doc.add_heading(text, level=min(level, 4))

        elif ttype == "paragraph":
            text = _extract_text(token.get("children", []))
            if text.strip():
                doc.add_paragraph(text)

        elif ttype == "list":
            children = token.get("children", [])
            for item in children:
                text = _extract_text(item.get("children", []))
                # Flatten nested paragraphs in list items
                for line in text.split("\n"):
                    line = line.strip()
                    if line:
                        doc.add_paragraph(line, style="List Bullet")

        elif ttype == "block_code":
            code = token.get("raw", token.get("text", ""))
            para = doc.add_paragraph()
            run = para.add_run(code)
            run.font.name = "Courier New"
            run.font.size = Pt(9)

        elif ttype == "thematic_break":
            doc.add_paragraph("─" * 40)

        elif ttype == "block_quote":
            text = _extract_text(token.get("children", []))
            para = doc.add_paragraph(text)
            para.style = "Quote" if "Quote" in [s.name for s in doc.styles] else None


def _extract_text(children: list) -> str:
    """Recursively extract plain text from mistune AST children."""
    parts = []
    for child in children:
        if isinstance(child, str):
            parts.append(child)
        elif isinstance(child, dict):
            ctype = child.get("type", "")
            if ctype in ("text", "codespan"):
                parts.append(child.get("raw", child.get("text", child.get("children", ""))))
            elif ctype == "paragraph":
                parts.append(_extract_text(child.get("children", [])))
            elif ctype == "list_item":
                parts.append(_extract_text(child.get("children", [])))
            elif "children" in child:
                c = child["children"]
                if isinstance(c, list):
                    parts.append(_extract_text(c))
                elif isinstance(c, str):
                    parts.append(c)
            elif "raw" in child:
                parts.append(child["raw"])
    return " ".join(parts)


# ─── Markdown → PPTX ──────────────────────────────────────────────────────

def export_pptx(
    markdown: str,
    output_path: str | Path,
    title: str = "Research Report",
) -> str:
    """
    Convert Markdown report to a PowerPoint presentation.
    Each H2 section becomes a slide.

    Args:
        markdown: Markdown content
        output_path: Output .pptx file path
        title: Presentation title

    Returns:
        Absolute path to generated file
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    prs = Presentation()

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    if slide.placeholders[1]:
        slide.placeholders[1].text = "Generated by Research Agent"

    # Split markdown by H2 sections
    sections = _split_by_headers(markdown)

    for section_title, section_content in sections:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = section_title

        # Add content as bullet points
        body = slide.placeholders[1]
        tf = body.text_frame
        tf.clear()

        lines = section_content.strip().split("\n")
        first = True
        for line in lines:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            # Strip markdown bullet markers
            if line.startswith("- ") or line.startswith("* "):
                line = line[2:]
            elif line.startswith("  - ") or line.startswith("  * "):
                line = line[4:]

            if first:
                tf.paragraphs[0].text = line[:200]
                tf.paragraphs[0].font.size = PptxPt(14)
                first = False
            else:
                p = tf.add_paragraph()
                p.text = line[:200]
                p.font.size = PptxPt(14)

    prs.save(str(output_path))
    return str(output_path.resolve())


def _split_by_headers(markdown: str) -> list[tuple[str, str]]:
    """Split markdown into (header, content) sections by H2 headers."""
    sections = []
    current_title = "Overview"
    current_lines: list[str] = []

    for line in markdown.split("\n"):
        if line.startswith("## "):
            if current_lines:
                sections.append((current_title, "\n".join(current_lines)))
            current_title = line[3:].strip()
            current_lines = []
        else:
            current_lines.append(line)

    if current_lines:
        sections.append((current_title, "\n".join(current_lines)))

    return sections


# ─── Markdown → LaTeX ─────────────────────────────────────────────────────

def export_latex(
    markdown: str,
    output_path: str | Path,
    title: str = "Research Report",
) -> str:
    """
    Convert Markdown report to LaTeX.

    Args:
        markdown: Markdown content
        output_path: Output .tex file path
        title: Document title

    Returns:
        Absolute path to generated file
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Convert markdown body to LaTeX
    with LaTeXRenderer() as renderer:
        body = renderer.render(mistletoe.Document(markdown))

    # Wrap in a full LaTeX document
    latex = f"""\\documentclass[12pt]{{article}}
\\usepackage[utf8]{{inputenc}}
\\usepackage[T1]{{fontenc}}
\\usepackage{{hyperref}}
\\usepackage{{amsmath}}
\\usepackage{{geometry}}
\\geometry{{margin=1in}}

\\title{{{_escape_latex(title)}}}
\\date{{\\today}}

\\begin{{document}}
\\maketitle

{body}

\\end{{document}}
"""
    output_path.write_text(latex, encoding="utf-8")
    return str(output_path.resolve())


def _escape_latex(text: str) -> str:
    """Escape special LaTeX characters."""
    for char in ["&", "%", "$", "#", "_", "{", "}"]:
        text = text.replace(char, f"\\{char}")
    return text
